project:
  type: website
  
header-includes:
  - '<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">'
  - '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>'
  - '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>'
  - |
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
          return new bootstrap.Tooltip(tooltipTriggerEl)
        })
      });
    </script>

website:
  title: "Documentation"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: false
  favicon: pophivelogo.png
  search: false
  repo-url: https://github.com/PopHIVE/processing-documentation
  issue-url: https://github.com/PopHIVE/processing-documentation/issues
  repo-actions: [source, issue]
  navbar:
    left:
      - text: "Childhood Immunizations"
        href: Pages/childhood-immunizations/childhood-immunizations.qmd
      - text: "Respiratory Diseases"
        menu:
          - text: "COVID-19"
            href: Pages/respiratory-diseases/covid.qmd
          - text: "Influenza"
            href: Pages/respiratory-diseases/influenza.qmd
          - text: "Pneumococcus"
            href: Pages/respiratory-diseases/pneumococcus.qmd
          - text: "Respiratory Syncytial Virus"
            href: Pages/respiratory-diseases/rsv.qmd
      - text: "Chronic Diseases"
        menu:
          - text: "Diabetes"
            href: Pages/chronic-diseases/diabetes.qmd
          - text: "Obesity"
            href: Pages/chronic-diseases/obesity.qmd
      - text: "Injury & Overdose"
        menu:
          - text: "Opioid Overdoses"
            href: Pages/injury-and-overdose/opioid-overdoses.qmd
    center:
      - text: PopHIVE.org
        href: https://www.pophive.org/
        target: _blank
  page-footer:
    background: light 
    left: |
      This site was built on a pophive.github.io page.
      <br>
      It was rendered using Quarto (v 1.6.39) and theme [sandstone](https://bootswatch.com/sandstone/).
    right:
      - text: '<span class="bi bi-globe" data-bs-toggle="tooltip" title="Visit PopHIVE.org"></span>'
        href: https://www.pophive.org/
        target: _blank
      - text: '<span class="bi bi-envelope-paper" data-bs-toggle="tooltip" title="Provide Feedback"></span>'
        href: https://docs.google.com/forms/d/e/1FAIpQLSchAasiq7ovCCNz9ussb7C2ntkZ-8Rjc7-tNSglkf5boS-A0w/viewform
        target: _blank

format:
  html:
    theme: sandstone
    css: _styles/styles.css
    toc: true



